using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace sciccorspaperrock
{
    class Program
    {
        static void Main(string[] args)
        {
            //1-initiate  2. generate random number fm system

            int userinput;
            string systemNum = "       ";
            int randomInt;
            // bool gameover = false;
            int gameover = 0;

            int userpoint = 0;
            int systempoint = 0;
            bool endgame = false;

            while (gameover <= 5 && endgame==false)
            {
                // . loop to check who win
                // look for the random number generated by system and set to match 

                Console.WriteLine("Key in paper =1,scissor= 2,rock =3, one choice only ");

                userinput = int.Parse(Console.ReadLine());


                Random num = new Random();
                randomInt = num.Next(1, 4);

                switch (randomInt)
                {
                // if randomInt is 1 - Case if 1
                    case 1:
                        systemNum = "PAPER";
                        Console.WriteLine("system is Paper");
                        if (userinput == 1)
                        {

                            Console.WriteLine("fair");
                        }
                        else if (userinput == 2)
                        {
                            Console.WriteLine("you win!");
                            userpoint++;

                        }

                        else if (userinput == 3)
                        {
                            Console.WriteLine("Systen win");
                            systempoint++;
                        }

                        break;
                    case 2:
                        systemNum = "SCISSOR";
                        Console.WriteLine("system is SCISSOR");
                        if (userinput == 1)
                        {

                            Console.WriteLine("SYSTEIM WIN");
                            systempoint++;
                        }
                        else if (userinput == 2)
                        {
                            Console.WriteLine("FAIR");


                        }

                        else if (userinput == 3)
                        {
                            Console.WriteLine("yOU win");
                            userpoint++;
                        }

                        break;

                    case 3:
                        systemNum = "ROCK";
                        Console.WriteLine("system is ROCK");
                        if (userinput == 1)
                        {

                            Console.WriteLine("You win!");
                            userpoint++;
                        }
                        else if (userinput == 2)
                        {
                            Console.WriteLine("system win!");
                            systempoint++;

                        }

                        else if (userinput == 3)
                        {
                            Console.WriteLine("fair");

                        }
                        break;


                        if (userinput != 1 && userinput != 2 && userinput != 3)

                        {
                            Console.WriteLine("   sorry !only 1 to 3  !");
                        }
                            break; 
                }


                gameover++;
                if (gameover > 5) 
                { endgame = true; }

                                
        }
            if (endgame == true)
            {
                Console.Write("results system: " + systempoint + " " + "   your result:   " + userpoint + "");
                if (systempoint > userpoint)
                {
                    Console.Write("System win");

                }
                else if (userpoint > systempoint)
                {
                    Console.Write("   congratulation  ! you win    ");
                }
                Console.ReadKey();
                
            }

        }

    }
}


